---

- name: 'download archive'
  ansible.builtin.get_url:
    url: '{{hashicorp_repo}}/nomad/{{item.version}}/nomad_{{item.version}}_{{hashicorp_arch}}.{{nomad_format}}'
    dest: '{{hashicorp_dir_staging}}/nomad_{{item.version}}_{{hashicorp_arch}}.{{nomad_format}}'
    timeout: '{{hashicorp_internet_timeout}}'
    validate_certs: false
  loop: '{{nomad_builds}}'
  when: item.state == 'present'
  tags: [ct-nomad]

- name: 'create package directories'
  ansible.builtin.file:
    state: directory
    owner: root
    group: root
    mode: '0755'
    path: '{{hashicorp_dir_pkg}}/nomad/{{item.version}}'
  loop: '{{nomad_builds}}'
  when: item.state == 'present'
  ignore_errors: '{{ansible_check_mode}}'
  become: true
  tags: [ct-nomad]

- name: 'expand archives'
  ansible.builtin.unarchive:
    src: '{{hashicorp_dir_staging}}/nomad_{{item.version}}_{{hashicorp_arch}}.{{nomad_format}}'
    dest: '{{hashicorp_dir_pkg}}/nomad/{{item.version}}'
    copy: false
  loop: '{{nomad_builds}}'
  when: item.state == 'present'
  ignore_errors: '{{ansible_check_mode}}'
  become: true
  tags: [ct-nomad]

- name: 'add symlink to active binary'
  ansible.builtin.file:
    dest: '{{hashicorp_dir_bin}}/nomad'
    src: '{{hashicorp_dir_pkg}}/nomad/{{nomad_version}}/nomad'
    state: link
  ignore_errors: '{{ansible_check_mode}}'
  become: true
  tags: [ct-nomad]

- name: 'system account'
  ansible.builtin.user:
    name: nomad
    comment: 'Nomad system account'
    system: true
    state: present
  become: true
  tags: [ct-nomad]

- name: 'bash include'
  ansible.builtin.template:
    src: nomad.sh.j2
    dest: /usr/local/etc/bash.d/nomad.sh
    owner: root
    group: root
    mode: 0644
  become: true
  tags: [ct-nomad]

- name: 'directories'
  ansible.builtin.file:
    state: directory
    path: '{{item}}'
    owner: root
    group: root
    mode: '0755'
  loop: '{{nomad_dirs}}'
  become: true
  tags: [ct-nomad]

- name: '{{nomad_role}} config file (NL)'
  ansible.builtin.template:
    backup: true
    dest: '{{nomad_etc_dir}}/{{nomad_role}}.hcl'
    group: root
    mode: '0600'
    owner: root
    src: '{{nomad_role}}.hcl.j2'
  notify: handler_restart_nomad
  no_log: true
  become: true
  tags: [ct-nomad]

- name: 'systemd unit file'
  ansible.builtin.template:
    src: nomad-{{nomad_role}}.service.j2
    dest: /etc/systemd/system/nomad-{{nomad_role}}.service
    owner: root
    group: root
    mode: '0600'
  register: reg_service
  become: true
  tags: [ct-nomad]

- name: 'nomad-{{nomad_role}} service to {{nomad_state}}'
  ansible.builtin.systemd:
    name: nomad-{{nomad_role}}
    state: '{{nomad_state}}'
    enabled: true
    daemon_reload: '{{reg_service is changed}}'
  become: true
  tags: [ct-nomad]

# --------------------------------
...
