---

- name: 'push bash include'
  template:
    src: nomad.sh.j2
    dest: /usr/local/etc/bash.d/nomad.sh
    owner: root
    group: root
    mode: 0644
  become: true
  tags:
  - ct-nomad

- name: 'download archive'
  get_url:
    url: '{{hashicorp_repo}}/nomad/{{nomad_version}}/{{nomad_target}}'
    dest: '{{hashicorp_dir_staging}}'
    timeout: '{{hashicorp_internet_timeout}}'
    validate_certs: false
  tags:
  - ct-nomad

- name: 'expand archive'
  unarchive:
    src: '{{hashicorp_dir_staging}}/{{nomad_target}}'
    dest: '{{hashicorp_dir_bin}}'
    copy: false
  become: true
  tags:
  - ct-nomad

# --------------------------------
...
