---
- name: 'handler_reload_nomad'
  systemd:
    state: reloaded
    name: nomad-{{nomad_role}}.service
  become: true

- name: 'handler_restart_nomad'
  systemd:
    state: restarted
    name: nomad-{{nomad_role}}.service
  become: true
...
